[package]
name = "rust-ligma"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
prettytable-rs = "^0.10"
tokio = { version = "1.15", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
dotenv = "^0.15"
